/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "surface-bright": "#313a44",
            "primary": "#99cbff",
            "on-primary-fixed": "#001d34",
            "on-tertiary-container": "#002a53",
            "on-secondary-container": "#b3edff",
            "primary-fixed-dim": "#99cbff",
            "surface": "#0b141d",
            "on-surface-variant": "#c0c7d2",
            "outline": "#8a919c",
            "surface-container-lowest": "#060f18",
            "on-tertiary": "#00315f",
            "tertiary-fixed-dim": "#a6c8ff",
            "secondary-container": "#007084",
            "on-secondary-fixed": "#001f26",
            "on-primary-fixed-variant": "#004a78",
            "inverse-surface": "#dae3f0",
            "secondary": "#81d2e9",
            "on-error": "#690005",
            "tertiary": "#a6c8ff",
            "surface-container": "#18202a",
            "on-error-container": "#ffdad6",
            "primary-fixed": "#cfe5ff",
            "inverse-on-surface": "#28313b",
            "on-tertiary-fixed": "#001c3b",
            "error": "#ffb4ab",
            "secondary-fixed": "#adecff",
            "outline-variant": "#404750",
            "surface-container-highest": "#2d3640",
            "surface-container-low": "#131c26",
            "surface-tint": "#99cbff",
            "on-primary-container": "#002c4a",
            "tertiary-container": "#6692d3",
            "surface-dim": "#0b141d",
            "on-background": "#dae3f0",
            "on-secondary-fixed-variant": "#004e5d",
            "on-surface": "#dae3f0",
            "on-tertiary-fixed-variant": "#0c4783",
            "inverse-primary": "#00629d",
            "tertiary-fixed": "#d5e3ff",
            "on-primary": "#003355",
            "primary-container": "#4096dd",
            "surface-container-high": "#222b34",
            "surface-variant": "#2d3640",
            "secondary-fixed-dim": "#81d2e9",
            "error-container": "#93000a",
            "background": "#0b141d",
            "on-secondary": "#003641"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "md": "24px",
            "xs": "4px",
            "lg": "48px",
            "sm": "12px",
            "gutter": "24px",
            "base": "8px",
            "margin-desktop": "64px",
            "margin-mobile": "16px",
            "xl": "80px",
            "section-gap": "32px"
        },
        "fontFamily": {
            "headline-lg-mobile": ["Poppins", "sans-serif"],
            "body-md": ["Poppins", "sans-serif"],
            "label-md": ["Poppins", "sans-serif"],
            "body-lg": ["Poppins", "sans-serif"],
            "headline-xl": ["Poppins", "sans-serif"],
            "label-sm": ["Poppins", "sans-serif"],
            "headline-lg": ["Poppins", "sans-serif"],
            "display-lg": ["Poppins", "sans-serif"]
        },
        "fontSize": {
            "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
            "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
            "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
            "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
            "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
            "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
            "display-lg": ["44px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
        }
    }
  },
  plugins: [],
}
